name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      
     
      - uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=element-plus&repo=element-plus
          path: profile/pin-element-plus-element-plus.svg
          token: ${{ secrets.GITHUB_TOKEN }}      
      - uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=wailsapp&repo=wails
          path: profile/pin-wailsapp-wails.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=flutter&repo=flutter
          path: profile/pin-flutter-flutter.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=vueuse&repo=vueuse
          path: profile/pin-vueuse-vueuse.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push